
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox2;

	private global::DE.DrawingArea drawingarea2;

	private global::Gtk.Entry direct_entry;

	private global::Gtk.VBox vbox1;

	private global::DE.RandomizeLabel randomizelabel1;

	private global::Gtk.Entry ext_entry;

	private global::Gtk.VButtonBox vbuttonbox1;

	private global::Gtk.Button button3;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Encryptor");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.drawingarea2 = new global::DE.DrawingArea();
		this.drawingarea2.Name = "drawingarea2";
		this.vbox2.Add(this.drawingarea2);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.drawingarea2]));
		w1.Position = 1;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.direct_entry = new global::Gtk.Entry();
		this.direct_entry.CanFocus = true;
		this.direct_entry.Name = "direct_entry";
		this.direct_entry.IsEditable = true;
		this.direct_entry.InvisibleChar = '•';
		this.vbox2.Add(this.direct_entry);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.direct_entry]));
		w2.Position = 2;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.randomizelabel1 = new global::DE.RandomizeLabel();
		this.randomizelabel1.Name = "randomizelabel1";
		this.vbox1.Add(this.randomizelabel1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.randomizelabel1]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.ext_entry = new global::Gtk.Entry();
		this.ext_entry.CanFocus = true;
		this.ext_entry.Name = "ext_entry";
		this.ext_entry.IsEditable = true;
		this.ext_entry.InvisibleChar = '•';
		this.vbox1.Add(this.ext_entry);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.ext_entry]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbuttonbox1 = new global::Gtk.VButtonBox();
		this.vbuttonbox1.Name = "vbuttonbox1";
		// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.button3 = new global::Gtk.Button();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString("Encrypt");
		this.vbuttonbox1.Add(this.button3);
		global::Gtk.ButtonBox.ButtonBoxChild w5 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.button3]));
		w5.Expand = false;
		w5.Fill = false;
		this.vbox1.Add(this.vbuttonbox1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbuttonbox1]));
		w6.Position = 2;
		this.vbox2.Add(this.vbox1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vbox1]));
		w7.Position = 4;
		this.Add(this.vbox2);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 184;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.direct_entry.TextInserted += new global::Gtk.TextInsertedHandler(this.OnDirectEntered);
		this.ext_entry.TextInserted += new global::Gtk.TextInsertedHandler(this.OnExtEntered);
		this.button3.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler(this.onButtonPress);
		this.button3.Clicked += new global::System.EventHandler(this.onButtonPress);
	}
}
